modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/FiguraMC/Figura/issues"
license = "LGPL-2.1"
displayURL = "https://github.com/FiguraMC/Figura"

[[mods]]
modId = "figura"
version = "${version}"
displayName = "Figura"
authors = "skyrina"
description = '''
Extensive customization of the Player model
'''
logoFile = "icon.png"

[modproperties.figura]
assets_version="${assets_version}"

[[dependencies.figura]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.figura]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
